### ISSUE TITLE
Upgrade from 2022.12.1 to latest.

### ISSUE THREAD

**Issue by wolfswolke** [AriaGomes/Unraid-Cloudflared-Tunnel#1]
Hello!
Just got a notification from Cloudflare saying i should upgrade my tunnel to the latest version.
Can you please update this docker?
And just wanted to say a big thanks for this Docker ^^
KR
ZKWolf

**Comment by wolfswolke** [comment]
Ok im stupid... i just noticed on reboot it downloads the new version ._.
Sorry!

**Comment by AriaGomes** [comment]
> Hello!
> Just got a notification from Cloudflare saying i should upgrade my tunnel to the latest version.
> Can you please update this docker?
> And just wanted to say a big thanks for this Docker ^^
> KR
> ZKWolf

Hey, can you try restarting your container? it should automatically grab the latest versions binary and run that on container start. look at the logs when you restart and check to see what version it is running when you restart the container. thanks 🙂

**Comment by AriaGomes** [comment]
> Ok im stupid... i just noticed on reboot it downloads the new version ._.
> Sorry!

no worries 😊
