### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by myxxmikeyxx** [AriaGomes/Unraid-Cloudflared-Tunnel#11]
Hello do you have an update for the container on unraid with a template with all the new optional tags?
I personally would not mind having them and sample text and they are ignored. I have cert.pem file that I need to add to it for a zero trust vnc tunnel. I am not sure how to use the env varaible because it says to point to a file and I don't see a folder in appdata to put the file since the container looks like it has no mounted storage.

**Comment by AriaGomes** [comment]
There is a new template that you can get from the unraid CA. You will have to enable reinstalls or remove your current container and get the new template from the unraid CA "store". You may be correct about mounted storage. I will see later today if there needs to be an update to the container or if I can just add this to the template. I will let you know what I find either way and get this supported in the container 😄

**Comment by myxxmikeyxx** [comment]
@AriaGomes Thank you so much. I was reading online and for the cert.pem it looks like I need to make a config. Here is the link I got that info from: [link here](https://developers.cloudflare.com/cloudflare-one/tutorials/vnc-client-in-browser/)
I really apricate this and how much work you've done. I don't know a lot about the docker setup and the differences with unraid so I am not of any help sadly but I did try and clone the repo and see what I could figure out, but no luck with the little time.

**Comment by AriaGomes** [comment]
No problem, happy to get the most out of the things I make 😄. I just finished looking into this. Looks like its possible to do without changing anything here. I will update the template to include an example to make this simpler. You can either wait a couple of hours for that to update or use the following steps below to replicate and get your Cert to be used by cloudflared.

I didn't use a Cert on my end to test I used the log and PID files but it should be the exact same process for your cert file.
I added these settings in Docker Desktop in my testing. (You can replicate this in Unraid when you edit the container)
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/01c81c69-42be-45f6-af70-3a94edbe76b8)

ignore the qbittorent folder thats from something else but the other files were genereated by cloudflared. You should be able to point to ur appdata path then put your cert in there and edit the variable TUNNEL_ORIGIN_CERT to the value of /appdata/cert.pem or something similar to this. When you start the container after that it should use this file. Let me know if you have any trouble with that. Again I will be updating the template if you prefer to wait for that. Unraid CA updates every 2 hours so it make take some time before you see the new template there

**Comment by AriaGomes** [comment]
I had to add these to my unraid anyway so i took some screenshot incase you needed them for more clarification
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/2580d23f-8e73-4d07-8365-b5b0523bf615)

Then change the cert env value
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/60bc054d-9cf1-4ad2-a8b2-bd1fc3f6effe)

This should give you what you need. I just updated the template (not sure when it will be live) as well. Let me know if this works for you

**Comment by myxxmikeyxx** [comment]
@AriaGomes Thank you for that, I read your message but forgot to close it.
It has been working great btw!
