### ISSUE TITLE
Container not auto starting despite being set to auto start

### ISSUE THREAD

**Issue by sirjjq** [AriaGomes/Unraid-Cloudflared-Tunnel#12]
It works fine if i manually start it but it will not auto start despite being set to auto start. on unraid using docker. power went out and all containers set to auto start started except for this container. Thanks

**Comment by dereklarmstrong** [comment]
This just recently started happening to me as well.  Starts back up fine but doesn't auto restart. 

Same setup. Unraid, using the community App Store template with auto update set to "true" in the template parameters.

**Comment by dereklarmstrong** [comment]
Found the problem most likely right after I commented.  

The repository field got blanked out somehow in the unraid template, just reinstalled to make sure I was pulling the right image and we will see how it goes. 

@sirjjq you ever get it fixed for you?
