### ISSUE TITLE
Question re CF Tunnel keep getting  prompted about new version

### ISSUE THREAD

**Issue by thorrrr** [AriaGomes/Unraid-Cloudflared-Tunnel#13]
HI
When going int CF Tunnels area i get informed about a new version.
What do i need to do it says just copy paste command but i see no instructions for Unraid template

**Comment by AriaGomes** [comment]
On the latest unraid template there should be an autoupdate environment variable that is set to false by default. you can change this to true or simply restarting the container will download the latest Cloudflared and will be up to date. Hope this answers your questions

**Comment by AriaGomes** [comment]
I'm not sure if I understood correctly to get it running you need just the token from the command and paste that token in the TUNNEL_TOKEN environment variable.
