### ISSUE TITLE
Cloudflared Update

### ISSUE THREAD

**Issue by vincolay** [AriaGomes/Unraid-Cloudflared-Tunnel#5]
Cloudflare has issued a new version of Cloudflared but the docker container is not pulling the new version.

**Comment by AriaGomes** [comment]
> Cloudflare has issued a new version of Cloudflared but the docker container is not pulling the new version.

Sorry for such a late reply. This container will grab the latest release on startup. Can you try restarting the container and check what version it has pulled?

**Comment by AriaGomes** [comment]
Closing this for now. If you still have issue please make a new issue and I will respond in more timely manner. Thanks
