### ISSUE TITLE
Time out Issue

### ISSUE THREAD

**Issue by myxxmikeyxx** [AriaGomes/Unraid-Cloudflared-Tunnel#6]
Hello this project has worked great for me. I have but one problem is the time out and stop running.
My area constantly has blips of power outages and sometimes they are enough to kill the internet. When that happens the modem has to reboot and sometimes takes a while and the container times out and stops. Any way to try to connect and after X tries it then adds like a 3 minute delay to try again or some way to configure it to do that? I just restart it manually right now but I am not always home when that happens and on travel for work then my other services like jellyfin and nextcloud are unreachable.

**Comment by AriaGomes** [comment]
Are you using the docker argument `--restart unless-stopped`? Are you using this inside of Unraid? Let me know and I can assist you further. If you have something like this the container should run regarless of your internet connection going out. The only thing that would be able to stop the container is a user actually giving the shut down command hence `unless-stopped`. Please take a look at that and let me know if it helps 😄.

[Link to Docker Doc about this](https://docs.docker.com/config/containers/start-containers-automatically/)

**Comment by myxxmikeyxx** [comment]
I am using the one on unraid from this project not sure if you know anything about it. I don't know what unraid default setting is. How would I check it in unraid or set it to that? An extra flag?

**Comment by AriaGomes** [comment]
I see, please ignore that then. On your unraid you should have and Autostart switch on the right side in your Docker section
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/5722802a-0959-4561-908e-6406e5b80f06)
Having that checked does exactly what I was explaining before its just a nice UI that will toggle this. Do you have this checked and it is still stopping? Let me know

**Comment by myxxmikeyxx** [comment]
Yes it is checked. After it failed to connect I think like three times (not sure I can try uplugging it and seeing it crash and then get the logs since I already fixed it) it then said connection failed times out (or soemthing like that in the log) and the container was stopped and I had manually restart it and then it worked because my internet was back by that point

**Comment by AriaGomes** [comment]
I think I understand now. I took a look at the cloudflared docs looks like the default retry attempt is 5
[https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/#retries](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/#retries) try adding a custom environement variable to the docker container in your unraiad docker management dashboard. Edit the container and scroll to the bottom. click on the following
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/0937e2ed-49ad-463a-a749-8e44d4b5f828)
Then fill out the following
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/465b18b4-b092-4d1c-ac18-8201cb51527b)
Click save and you should have this
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/e4bad703-03ee-4c4c-ad70-38c9e403a094)
Hit on Apply and it will rerun with the new env variable. You can verify in the logs and you should see something like this
![image](https://github.com/AriaGomes/Unraid-Cloudflared-Tunnel/assets/55286223/f8b807fc-882f-4b94-877a-54acc56dbc32)

There seems to be alot of new documentation of env varaibles. I will update the readme to include these and I will prob update the template in the CA Apps. Let me know if this works for you and if you have any other concerns

**Comment by myxxmikeyxx** [comment]
I have not been able to try this yet but I did make the change. I am having a different problem with unriad right now. I will hopefully be able to test this soon (possibly this weekend).
