### ISSUE TITLE
'TUNNEL_TOKEN' should be used instead of 'tunnel'

### ISSUE THREAD

**Issue by cjohnson46** [AriaGomes/Unraid-Cloudflared-Tunnel#8]
Fix: change template variable key to "TUNNEL_TOKEN" instead of "tunnel"

Problem:  I'm not sure how much of a problem this is but while looking through the container logs I noticed a warning: 'TUNNEL_TOKEN' should be used instead of 'tunnel'.  I changed the variable key to "TUNNEL_TOKEN" instead of "tunnel" and the error went away. 

Thank you for this container!

**Comment by AriaGomes** [comment]
Yea this warning was added by me in the latest update. If you regrab the template from the CA unraid "store" it will use `TUNNEL_TOKEN` as default. I can see how this might be confusing if you have the old template with the new updated container. Not to sure what to do about that, but going forward it should be straight forward for new users. :)
